site_name: solarith
site_url: https://solarith.dev
theme:
  name: material
  logo: assets/sun-2-svgrepo-com.svg
  favicon: assets/sun-2-svgrepo-com.svg
  palette: 
    scheme: slate
    primary: deep purple
    accent: indigo
  features:
    - content.code.copy
    - navigation.footer
extra:
  generator: false
  
markdown_extensions:
# code blocks: syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
# admonitions
  - admonition
  - pymdownx.details
#  - pymdownx.superfences

copyright: Copyright &copy; 2024 solarith
